version: '3'


services:
  myapi:
    build: ./myapi
    container_name: myapi
   
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7000:8000"

  minombre:
    build: ./minombre
    container_name: minombre
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

    ports:
      - "7001:8001"
  